[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "npm install --prefix frontend"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "npm start"