[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "cd frontend && npm ci --include=dev"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "npm start"